package com.example.lockedindungeon.activities

import android.app.Activity
import android.net.Uri
import android.os.Bundle
import android.util.Log
import android.webkit.WebView
import androidx.core.content.FileProvider.getUriForFile
import com.example.lockedindungeon.utils.RedirectTokenManager
import java.io.File
import java.io.IOException

class BlockActivity : Activity() {

    companion object {
        val tag : String = "BlockActivity"
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val intentData = intent.data
        val token = intentData?.getQueryParameter("token")

        if (!RedirectTokenManager.validateToken(token)) {
            Log.e(tag, "Invalid or missing redirection token. Closing.")
            finish()
            return
        }

        val webView = WebView(this).apply {
            settings.allowFileAccess = true
            settings.allowContentAccess = true // CRITICAL: Allows reading content:// URIs
        }

        setContentView(webView)

        // The content URI generated by your FileProvider
        val contentUriString : String = getUri()?.toString() ?: throw IOException("Failed to get content uri for bllocking page")

        if (intentData != null && intentData.authority == "com.example.lockedindungeon") {
            // Strip the token query parameter before loading in WebView
            // so FileProvider can find the actual file path.
            val cleanUri = intentData.buildUpon().clearQuery().build()
            webView.loadUrl(cleanUri.toString())
        } else {
            // Fallback
            val contentUriString : String = getUri()?.toString() ?: throw IOException("Failed to get content uri for bllocking page")
            webView.loadUrl(contentUriString)
        }
    }


    fun getUri(): Uri? {
        val filePath: File = File(this.filesDir, "block")
        val newFile = File(filePath, "block-page.html")
        val contentUri: Uri? = getUriForFile(this, "com.example.lockedindungeon", newFile)
        return contentUri
    }
}